apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: managed-standard-retain
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: managed-standard-retain
  resources:
    requests:
      storage: 1Gi
